### ISSUE TITLE
Cannot read property 'parseSignedCookie' of undefined

### ISSUE THREAD

**Issue by wangxuq** [senchalabs/connect#1072]
这个问题如何解决呢？
<pre>
var parseSignedCookie = require('connect').utils.parseSignedCookie;
                                                ^
TypeError: Cannot read property 'parseSignedCookie' of undefined
    at Object.<anonymous> (E:\nodejs\lianxi\chat\app.js:14:49)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
</pre>

**Comment by jordonias** [comment]
https://github.com/senchalabs/connect/issues/1040

**Comment by wangxuq** [comment]
thanks，I use connect@2.8.8 fix the problem.

**Comment by jordonias** [comment]
Your other option is to use connect 3 with https://github.com/expressjs/cookie-parser

**Comment by wangxuq** [comment]
yes,It also can chose this solution...thanks for your help

**Comment by dougwilson** [comment]
:+1:
