### ISSUE TITLE
TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by 11510746** [senchalabs/connect#1119]
#### OS
ubuntu16 (docker)
#### Nodes version
```sh
├─┬ connect@3.7.0 (git://github.com/senchalabs/connect.git#fa8916e6350e01262e86ccee82f490c65e04c728)
├─┬ connect-form@0.2.1
├─┬ connect-redis@3.4.2
```
#### Report
```sh
lib/response.js:19
  , send = connect.static.send
                          ^

TypeError: Cannot read property 'send' of undefined
    at Object.<anonymous> (/root/quicklisp/local-projects/resolve/exp/bin/temp-manual-subj/express/62257bce187ae673940fa59da2a06ca2b7d0729b-42fc0f9-860b4f1/lib/response.js:19:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/quicklisp/local-projects/resolve/exp/bin/temp-manual-subj/express/62257bce187ae673940fa59da2a06ca2b7d0729b-42fc0f9-860b4f1/lib/application.js:16:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/quicklisp/local-projects/resolve/exp/bin/temp-manual-subj/express/62257bce187ae673940fa59da2a06ca2b7d0729b-42fc0f9-860b4f1/lib/express.js:13:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/quicklisp/local-projects/resolve/exp/bin/temp-manual-subj/express/62257bce187ae673940fa59da2a06ca2b7d0729b-42fc0f9-860b4f1/index.js:2:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/quicklisp/local-projects/resolve/exp/bin/temp-manual-subj/express/62257bce187ae673940fa59da2a06ca2b7d0729b-42fc0f9-860b4f1/test/express.js:2:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /root/quicklisp/local-projects/resolve/exp/bin/temp-manual-subj/express/62257bce187ae673940fa59da2a06ca2b7d0729b-42fc0f9-860b4f1/node_modules/mocha/bin/mocha:95:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/root/quicklisp/local-projects/resolve/exp/bin/temp-manual-subj/express/62257bce187ae673940fa59da2a06ca2b7d0729b-42fc0f9-860b4f1/node_modules/mocha/bin/mocha:92:7)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by 11510746** [comment]
I solved it by using `connect@2.30.2`.
This kind of problems seems to be solved by downgrading the version.
